### ISSUE TITLE
[Bug] Back button always exits the app

### ISSUE THREAD

**Issue by JonnyHaystack** [LunaSeaApp/LunaSea#211] opened 2020-05-15 12:36 UTC
**Describe the Bug**
The back button seems to exit the app in a lot of situations where it should instead go back to the previous screen.

**To Reproduce**
1. Open the app
2. Tap on Sonarr, Radarr, Lidarr or similar
3. Press the back button and observe that the app closes

**Expected Behaviour**
The back button should return you to the previous screen, unless you are on the home screen in which case it should exit the app.

**Screenshots**

**Versions**
2.2.0

**Additional context**
This is on Android. I don't know about iOS.

**Comment by JagandeepBrar** [comment] 2020-05-15 20:25
This is by design, because of the way that routes are handled, if I push ontop of the stack a back arrow is shown instead of the drawer, so each time you change services I need to pop all current routes, and push the new route.

I will investigate a way around this, maybe the back button can open the drawer instead of closing the application.

This is likely the class I need to implement, so I am leaving a link for personal reference: https://api.flutter.dev/flutter/widgets/WillPopScope-class.html

**Comment by JagandeepBrar** [comment] 2020-05-20 21:53
This has now been implemented internally and will be live in the next beta update going live this week!

https://github.com/LunaSeaApp/LunaSea/commit/329768964e641d7bafc419f3d089749439685dea

**Closed by JagandeepBrar** 2020-05-20 21:53 UTC
Labels: bug
